# Generated by Django 4.2 on 2023-10-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='address',
            field=models.CharField(blank=True, help_text='Where customers will pick up their orders', max_length=200, null=True),
        ),
    ]
