# Generated by Django 4.2 on 2023-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_configurations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='address',
            field=models.CharField(blank=True, help_text='If this is not empty, it will show up on the contact page.', max_length=200, null=True),
        ),
    ]
