# Generated by Django 4.2.8 on 2023-12-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_configurations_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configurations',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
