# Generated by Django 4.2 on 2023-10-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='name',
            field=models.CharField(blank=True, help_text='Your name', max_length=255, null=True),
        ),
    ]
