# Generated by Django 4.2 on 2023-10-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_configurations_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurations',
            name='name',
        ),
    ]
